import json
from typing import Dict, Any
import google.generativeai as genai
from config import GEMINI_API_KEY, GEMINI_MODEL

genai.configure(api_key=GEMINI_API_KEY)


def build_synthesis_prompt(topic: str, analysis_data: Dict) -> str:
    meta = analysis_data.get("meta_analysis", {})
    aggregate = analysis_data.get("aggregate", {})
    individual = analysis_data.get("individual_analyses", [])

    facts_list = []
    insights_list = []
    for a in individual:
        facts_list.extend(a.get("key_facts", []))
        insights_list.extend(a.get("insights", []))

    return f"""Research Topic: {topic}

Key Themes: {', '.join(meta.get('cross_cutting_themes', aggregate.get('unique_themes', [])))}

Key Takeaways: {json.dumps(meta.get('key_takeaways', []))}

Important Facts:
{chr(10).join(f'- {f}' for f in facts_list[:20])}

Analytical Insights:
{chr(10).join(f'- {i}' for i in insights_list[:10])}

Key Entities: {', '.join(aggregate.get('unique_entities', [])[:20])}

Confidence Level: {meta.get('confidence_level', 'medium')}
Average Source Reliability: {aggregate.get('average_reliability', 0.6)}

Known Contradictions: {json.dumps(meta.get('contradictions', []))}

Gaps to Address: {json.dumps(meta.get('recommended_focus_areas', []))}"""


def run_synthesizer(topic: str, analysis_data: Dict) -> Dict[str, Any]:
    synthesis_context = build_synthesis_prompt(topic, analysis_data)

    system = """You are an expert research synthesizer. Create comprehensive, well-structured research reports that synthesize multiple sources into coherent narratives.

Your reports must follow this EXACT structure with proper markdown:

# [Descriptive Title]

## Executive Summary
2-3 paragraph overview of key findings and significance.

## Background & Context
Historical context and why this topic matters.

## Key Findings

### Finding 1: [Name]
Detailed explanation with evidence...

### Finding 2: [Name]
...

### Finding 3: [Name]
...

## Analysis & Insights
Deep analytical section connecting findings and drawing conclusions.

## Implications & Applications
Real-world implications and practical applications.

## Challenges & Limitations
Known challenges, contradictions, and limitations in current knowledge.

## Future Outlook
Trends, predictions, and areas for future development.

## Conclusion
Strong concluding synthesis tying everything together.

---
*Report generated by Multi-Agent Research Synthesizer*

Write thoroughly, professionally, and with depth. Minimum 1000 words."""

    model = genai.GenerativeModel(
        GEMINI_MODEL,
        system_instruction=system,
        generation_config=genai.GenerationConfig(temperature=0.4, max_output_tokens=3000)
    )
    response = model.generate_content(f"Synthesize this research data into a comprehensive report:\n\n{synthesis_context}")
    report_content = response.text

    word_count = len(report_content.split())
    section_count = report_content.count("## ")

    return {
        "report": report_content,
        "metadata": {
            "word_count": word_count,
            "section_count": section_count,
            "topics_covered": len(analysis_data.get("individual_analyses", [])),
            "confidence": analysis_data.get("meta_analysis", {}).get("confidence_level", "medium")
        }
    }
